### ISSUE TITLE
WorldGuard protection

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#4] opened 2019-11-19 04:59 UTC
Spigot 1.14.4
TreeFeller 1.9.3

It looks like TreeFeller blocks in any WorldGuard region, including
```
regions:
  __global__:
...
```
which is the entire world. So if WorldGuard is installed, TreeFeller is effectively disabled. IMHO, TreeFeller should be blocked only in WorldGuard regions listed in config.yml, and only if
```
    flags:
      block-break: allow
```
or
```
    flags:
      build: allow
```
is not set (which is the default).

**Comment by ThizThizzyDizzy** [comment] 2019-11-19 14:12
TreeFeller _should_ only block in regions the player doesn't have block-break access to...
The problem is this line:
`query.testState(location, player, Flags.BLOCK_BREAK)`
That returns `true` or `false` based on the flag, rather than `allow`, `deny`, and `none`
I assumed that `true` meant the player has access, and `false` meant they didn't, and it seemed to work when I tested it.

**Comment by ThizThizzyDizzy** [comment] 2019-11-19 14:25
Alright, figured it out
It's only checking the `block-break` flag

**Comment by ThizThizzyDizzy** [comment] 2019-11-19 14:32
And now I find I can use `queryState` instead of `testState` to get the allow/deny/etc.

**Comment by ThizThizzyDizzy** [comment] 2019-11-19 14:49
Fixed in 1.9.4

**Closed by ThizThizzyDizzy** 2019-11-19 14:49 UTC

**Comment by SlimeDog** [comment] 2019-11-19 15:29
Looks OK to me, in 1.9.4. Thanks.
